## Group Password

A `Password` object has the following attributes:

+ `length` (required) - minimum length of the generated password, must be a numer larger than or equal to 3
+ `upperLetters` - should the generated password contain uppercase letters
+ `lowerLetters` - should the generated password contain lowercase letters
+ `digits` - should the generated password contain digits
+ `id` (required) - unique identifier of the stored password
+ `password` (required) - the password
+ `hint` (required) - user-defined hint for the password
+ `userId` (required) - id of the user who created the password
+ `dateCreated` (required) - time and date when the password was created

# Get Password [/Password/{id}]
# Get Password [GET]
Get an existing password by id.

+ Parameters

    + id: 6 - Unique identifier of a stored password

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "password": "znj",
              "id": "527c4104-f8c5-4022-8291-f84025482c26",
              "hint": "user@mail.com",
              "userId" : "527c4104-f8c5-4022-8291-f84025482c26",
              "dateCreated": "2016-11-10T18:58:00.99815"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "password",
                "id",
                "hint",
                "userid",
                "dateCreated"
              ]
            }

+ Response 404 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

# Generate Password [/Password]
## Generate Password [POST]
Generate random password.

+ Request (application/json)

        {
            "length": 3,
            "upperLetters": true,
            "lowerLetters": true,
            "digits": true,
        }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "length": {
                  "type": "number",
                  "minimum": 3,
                  "exclusiveMinimum": false
                },
                "upperLetters": {
                  "type": "boolean"
                },
                "lowerLetters": {
                  "type": "boolean"
                },
                "digits": {
                  "type": "boolean"
                }
              },
              "required": [
                "length"
              ]
            }

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "password": "znj",
              "id": "527c4104-f8c5-4022-8291-f84025482c26",
              "hint": "user@mail.com",
              "userId" : "527c4104-f8c5-4022-8291-f84025482c26",
              "dateCreated": "2016-11-10T18:58:00.99815"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "password",
                "id",
                "hint",
                "userid",
                "dateCreated"
              ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

# Update Password [/Password/{id}]
# Update Password [PUT]
Update an existing password.

+ Parameters

    + id: 6 - Unique identifier of a stored password

+ Request (application/json)

        {
            "id": 6
        }

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "password": "znj",
              "id": "527c4104-f8c5-4022-8291-f84025482c26",
              "hint": "user@mail.com",
              "userId" : "527c4104-f8c5-4022-8291-f84025482c26",
              "dateCreated": "2016-11-10T18:58:00.99815"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "password",
                "id",
                "hint",
                "userid",
                "dateCreated"
              ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

# Delete Password [/Password/{id}]
# Delete Password [DELETE]
Delete an existing password.

+ Parameters

    + id: 6 - Unique identifier of a stored password

+ Response 200 (application/json; charset=utf-8)