## Group Password

A `Password` object has the following attributes:

+ `length` (required) - minimum length of the generated password, must be a numer larger than or equal to 3
+ `upperCase` - number of uppercase letters in the generated password 
+ `lowerCase` - number of lowercase letters in the generated password
+ `digits` - number of digits in the generated password
+ `symbols` - number of non-alphanumeric symbols in the generated password
+ `id` - unique identifier of the stored password
+ `password` (required) - the generated password
+ `hint` - user-defined hint for the password
+ `userId` - id of the user who created the password
+ `dateCreated` (required) - time and date when the password was created

# Get Password [/Password/{id}]
# Get Password [GET]
Get an existing password by id.

+ Parameters

    + id: 10 - Unique identifier of a stored password

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "id": 10,
              "password": "0rtPcK",
              "hint": "fake",
              "userId" : "527c4104-f8c5-4022-8291-f84025482c26",
              "dateCreated": "2016-11-13T23:43:17.353178"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "id": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "id",
                "password",
                "hint",
                "userid",
                "dateCreated"
              ]
            }

+ Response 404 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

+ Response 401 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

# Generate Password [/Password]
## Generate Password [POST]
Generate random password.

+ Request (application/json)

        {
            "length": 8,
            "upperCase": 2,
            "lowerCase": 4,
            "digits": 1,
            "symbols": 1,
            "hint": "it's a hint."
        }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "length": {
                  "type": "number"
                },
                "upperCase": {
                  "type": "number"
                },
                "lowerCase": {
                  "type": "number"
                },
                "digits": {
                  "type": "number"
                },
                "symbols": {
                  "type": "number"
                },
                "hint": {
                  "type": "string"
                }
              },
              "required": [
                "length"
              ]
            }

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "password": "znj",
              "dateCreated": "2016-11-10T18:58:00.99815"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "id": {
                  "type": "number"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "password",
                "dateCreated"
              ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {
              "success": false,
              "verbose": {} 
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "verbose": {
                  "type": "object"
                }
              },
              "required": [
                "success",
                "verbose"
              ]
            }

# Update Password [/Password/{id}]
# Update Password [PUT]
Update an existing password.

+ Parameters

    + id: 6 - Unique identifier of a stored password

+ Request (application/json)

        {
            "id": 6
        }

+ Response 200 (application/json; charset=utf-8)
    + Body

            {
              "success": true,
              "password": "znj",
              "id": "527c4104-f8c5-4022-8291-f84025482c26",
              "hint": "user@mail.com",
              "userId" : "527c4104-f8c5-4022-8291-f84025482c26",
              "dateCreated": "2016-11-10T18:58:00.99815"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "password": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "hint": {
                  "type": "string"
                },
                "userId": {
                  "type": "string"
                },
                "dateCreated": {
                  "type": "string"
                }
              },
              "required": [
                "success",
                "password",
                "id",
                "hint",
                "userid",
                "dateCreated"
              ]
            }

+ Response 400 (application/json; charset=utf-8)
    + Body

            {
              "success": false
            }

    + Schema


            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                }
              },
              "required": [
                "success"
              ]
            }

# Delete Password [/Password/{id}]
# Delete Password [DELETE]
Delete an existing password.

+ Parameters

    + id: 6 - Unique identifier of a stored password

+ Response 200 (application/json; charset=utf-8)