FORMAT: 1A
HOST: http://localhost:5000/api

# RandomPasswordGenerator API docs

# About

RandomPasswordGenerator is REST API for generating random passwords.<br><br><br>

# Date and time format

Dates are represented using the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard and format with timezone.

Example: `2016-11-10T23:19:16.16519+01:00`<br><br><br>

## Group Account

An `Account` object has the following attributes:

+ `id` (required) - unique identifier of the user
+ `name` (required) - the user's name
+ `email` (required) - email of the user
+ `dateCreated` (required) - time and date when the user account was created

<!-- include(Register.apib) -->

<!-- include(Login.apib) -->

<!-- include(Logout.apib) -->

<!-- include(User.apib) -->

<!-- include(Password.apib) -->
